FROM alpine:latest

# https://mirrors.alpinelinux.org/
RUN sed -i 's@dl-cdn.alpinelinux.org@ftp.halifax.rwth-aachen.de@g' /etc/apk/repositories

RUN apk update
RUN apk upgrade

# required h2o 
RUN apk add --no-cache \
  gcc make linux-headers musl-dev zlib-dev zlib-static \
  python3-dev curl zstd-static zstd-dev openssl-dev openssl-libs-static \
  g++ git libuv-static libuv-dev libcap-static libcap-dev \
  cmake ninja ruby mruby mruby-dev ruby-rake perl \
  autoconf automake libtool bison liburing-dev bash xz

ENV XZ_OPT=-e9
COPY build-static-h2o.sh  build-static-h2o.sh
RUN chmod +x ./build-static-h2o.sh
RUN bash ./build-static-h2o.sh
